### ISSUE TITLE
Nodes Type Filter broken

### ISSUE THREAD

**Issue by ErwanDemairy** [Wimmics/gephi-semantic-web-import#3]
log obtained. Check the SPARQL request used to filter, from the log it appears to not to be syntactically correct anymore.
```log
Apr 20, 2023 3:43:19 PM fr.inria.edelweiss.sparql.corese.CoreseDriver loadFile -- SEVERE: Exception in loadFile:fr.inria.corese.sparql.triple.javacc1.JavaccParseException: Encountered "/" at line 1, column 1. -- Was expecting one of: --     <EOF>  --     "@base" ... --     "@prefix" ... --     "@path" ... --     <LANGTAG> ... --     "base" ... --     "prefix" ... --     "select" ... --     "describe" ... --     "construct" ... --     "rule" ... --     "ask" ... --     "template" ... --     "load" ... --     "clear" ... --     "drop" ... --     "create" ... --     "add" ... --     "move" ... --     "copy" ... --     "insert" ... --     "delete" ... --     "with" ... --     "function" ... --     "package" ... --     "{" ... --      -- 
Apr 20, 2023 3:43:19 PM org.netbeans.core.startup.TopLogging$AWTHandler uncaughtException -- SEVERE: null -- java.lang.RuntimeException: fr.inria.corese.sparql.exceptions.QuerySyntaxException: fr.inria.corese.sparql.triple.javacc1.JavaccParseException: Encountered "/" at line 1, column 1. -- Was expecting one of: --     <EOF>  --     "@base" ... --     "@prefix" ... --     "@path" ... --     <LANGTAG> ... --     "base" ... --     "prefix" ... --     "select" ... --     "describe" ... --     "construct" ... --     "rule" ... --     "ask" ... --     "template" ... --     "load" ... --     "clear" ... --     "drop" ... --     "create" ... --     "add" ... --     "move" ... --     "copy" ... --     "insert" ... --     "delete" ... --     "with" ... --     "function" ... --     "package" ... --     "{" ... --      -- 	at fr.inria.edelweiss.sparql.corese.CoreseDriver.loadFile(CoreseDriver.java:142) -- 	at fr.inria.edelweiss.sparql.corese.CoreseDriver.init(CoreseDriver.java:64) -- 	at fr.inria.edelweiss.semantic.SemanticWebImportMainWindowTopComponent.selectOnGraph(SemanticWebImportMainWindowTopComponent.java:985) -- 	at fr.inria.wimmics.semanticweb.filter.instance.InstanceFilter.filter(InstanceFilter.java:64) -- 	at org.gephi.filters.FilterProcessor.process(FilterProcessor.java:128) -- 	at org.gephi.filters.FilterThread.filter(FilterThread.java:149) -- 	at org.gephi.filters.FilterThread.run(FilterThread.java:121) -- Caused by: fr.inria.corese.sparql.exceptions.QuerySyntaxException: fr.inria.corese.sparql.triple.javacc1.JavaccParseException: Encountered "/" at line 1, column 1. -- Was expecting one of: --     <EOF>  --     "@base" ... --     "@prefix" ... --     "@path" ... --     <LANGTAG> ... --     "base" ... --     "prefix" ... --     "select" ... --     "describe" ... --     "construct" ... --     "rule" ... --     "ask" ... --     "template" ... --     "load" ... --     "clear" ... --     "drop" ... --     "create" ... --     "add" ... --     "move" ... --     "copy" ... --     "insert" ... --     "delete" ... --     "with" ... --     "function" ... --     "package" ... --     "{" ... --      -- 	at fr.inria.corese.sparql.triple.parser.ParserSparql1.parse(ParserSparql1.java:79) -- 	at fr.inria.corese.compiler.parser.Transformer.parse(Transformer.java:212) -- 	at fr.inria.corese.compiler.parser.Transformer.parse(Transformer.java:196) -- 	at fr.inria.corese.compiler.eval.QuerySolver.parse(QuerySolver.java:647) -- 	at fr.inria.corese.compiler.eval.QuerySolver.parse(QuerySolver.java:642) -- 	at fr.inria.edelweiss.sparql.corese.CoreseDriver.loadFile(CoreseDriver.java:132) -- 	... 6 more -- Caused by: fr.inria.corese.sparql.triple.javacc1.JavaccParseException: Encountered "/" at line 1, column 1. -- Was expecting one of: --     <EOF>  --     "@base" ... --     "@prefix" ... --     "@path" ... --     <LANGTAG> ... --     "base" ... --     "prefix" ... --     "select" ... --     "describe" ... --     "construct" ... --     "rule" ... --     "ask" ... --     "template" ... --     "load" ... --     "clear" ... --     "drop" ... --     "create" ... --     "add" ... --     "move" ... --     "copy" ... --     "insert" ... --     "delete" ... --     "with" ... --     "function" ... --     "package" ... --     "{" ... --      -- 	at fr.inria.corese.sparql.triple.javacc1.SparqlCorese.parse(SparqlCorese.java:102) -- 	at fr.inria.corese.sparql.triple.parser.ParserSparql1.parse(ParserSparql1.java:70) -- 	... 11 more --  -- 
Apr 20, 2023 3:45:45 PM fr.inria.edelweiss.sparql.corese.CoreseDriver init -- INFO: loading /var/folders/dn/_b9lzwr96x38wn6kptvg3ftc0000gq/T/tempLastRdf9860513673656796977.rdf -- 
```

**Comment by ErwanDemairy** [comment]
same issue than #6
