### ISSUE TITLE
Unable to open local files on Windows

### ISSUE THREAD

**Issue by donpellegrino** [Wimmics/gephi-semantic-web-import#5]
## Which Plugin?

Semantic Web Import

## Expected Behavior

When using Local Driver - Corese and the "+" button to add local .ttl files, the files will load.

## Current Behavior

If adding to the RDF resources list with "+" and the file selection dialog, errors beginning with unexpected "C:" are reported

```
Nov 16, 2023 10:48:41 AM fr.inria.edelweiss.sparql.corese.CoreseDriver loadFile
 -- SEVERE: Exception in loadFile:fr.inria.corese.sparql.triple.javacc1.JavaccParseException: Encountered "C:" at line 1, column 1.
 -- Was expecting one of:
 --     <EOF> 
 --     "@base" ...
 --     "@prefix" ...
 --     "@path" ...
 --     <LANGTAG> ...
 --     "base" ...
 --     "prefix" ...
 --     "select" ...
 --     "describe" ...
 --     "construct" ...
 --     "rule" ...
 --     "ask" ...
 --     "template" ...
 --     "load" ...
 --     "clear" ...
 --     "drop" ...
 --     "create" ...
 --     "add" ...
 --     "move" ...
 --     "copy" ...
 --     "insert" ...
 --     "delete" ...
 --     "with" ...
 --     "function" ...
 --     "package" ...
 --     "{" ...
 --     
 -- 
Nov 16, 2023 10:48:41 AM org.netbeans.core.startup.TopLogging$AWTHandler uncaughtException
 -- SEVERE: null
 -- java.lang.RuntimeException: fr.inria.corese.sparql.exceptions.QuerySyntaxException: fr.inria.corese.sparql.triple.javacc1.JavaccParseException: Encountered "C:" at line 1, column 1.
 -- Was expecting one of:
 --     <EOF> 
 --     "@base" ...
 --     "@prefix" ...
 --     "@path" ...
 --     <LANGTAG> ...
 --     "base" ...
 --     "prefix" ...
 --     "select" ...
 --     "describe" ...
 --     "construct" ...
 --     "rule" ...
 --     "ask" ...
 --     "template" ...
 --     "load" ...
 --     "clear" ...
 --     "drop" ...
 --     "create" ...
 --     "add" ...
 --     "move" ...
 --     "copy" ...
 --     "insert" ...
 --     "delete" ...
 --     "with" ...
 --     "function" ...
 --     "package" ...
 --     "{" ...
 --     
 -- 	at fr.inria.edelweiss.sparql.corese.CoreseDriver.loadFile(CoreseDriver.java:142)
 -- 	at fr.inria.edelweiss.sparql.corese.CoreseDriver.init(CoreseDriver.java:64)
 -- 	at fr.inria.edelweiss.semantic.importer.SemanticWebImportParser.initAnalyzer(SemanticWebImportParser.java:126)
 -- 	at fr.inria.edelweiss.semantic.importer.SemanticWebImportParser.populateRDFGraph(SemanticWebImportParser.java:97)
 -- 	at fr.inria.edelweiss.semantic.SemanticWebImportMainWindowTopComponent.startCreateGraphs(SemanticWebImportMainWindowTopComponent.java:841)
 -- 	at fr.inria.edelweiss.semantic.SemanticWebImportMainWindowTopComponent.startCreateGraphsAction(SemanticWebImportMainWindowTopComponent.java:821)
 -- 	at fr.inria.edelweiss.semantic.SemanticWebImportMainWindowTopComponent$15.actionPerformed(SemanticWebImportMainWindowTopComponent.java:740)
 -- 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
 -- 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
 -- 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
 -- 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
 -- 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
 -- 	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
 -- 	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
 -- 	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
 -- 	at java.desktop/java.awt.Component.processEvent(Unknown Source)
 -- 	at java.desktop/java.awt.Container.processEvent(Unknown Source)
 -- 	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
 -- 	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 -- 	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 -- 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
 -- 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
 -- 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
 -- 	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
 -- 	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
 -- 	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
 -- 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 -- 	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 -- 	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 -- 	at java.base/java.security.AccessController.doPrivileged(Native Method)
 -- 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 -- 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 -- 	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 -- 	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
 -- 	at java.base/java.security.AccessController.doPrivileged(Native Method)
 -- 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 -- 	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
 -- 	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
 -- 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 -- 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 -- 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 -- 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 -- 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 -- 	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
 -- Caused by: fr.inria.corese.sparql.exceptions.QuerySyntaxException: fr.inria.corese.sparql.triple.javacc1.JavaccParseException: Encountered "C:" at line 1, column 1.
 -- Was expecting one of:
 --     <EOF> 
 --     "@base" ...
 --     "@prefix" ...
 --     "@path" ...
 --     <LANGTAG> ...
 --     "base" ...
 --     "prefix" ...
 --     "select" ...
 --     "describe" ...
 --     "construct" ...
 --     "rule" ...
 --     "ask" ...
 --     "template" ...
 --     "load" ...
 --     "clear" ...
 --     "drop" ...
 --     "create" ...
 --     "add" ...
 --     "move" ...
 --     "copy" ...
 --     "insert" ...
 --     "delete" ...
 --     "with" ...
 --     "function" ...
 --     "package" ...
 --     "{" ...
 --     
 -- 	at fr.inria.corese.sparql.triple.parser.ParserSparql1.parse(ParserSparql1.java:79)
 -- 	at fr.inria.corese.compiler.parser.Transformer.parse(Transformer.java:212)
 -- 	at fr.inria.corese.compiler.parser.Transformer.parse(Transformer.java:196)
 -- 	at fr.inria.corese.compiler.eval.QuerySolver.parse(QuerySolver.java:647)
 -- 	at fr.inria.corese.compiler.eval.QuerySolver.parse(QuerySolver.java:642)
 -- 	at fr.inria.edelweiss.sparql.corese.CoreseDriver.loadFile(CoreseDriver.java:132)
 -- 	... 43 more
 -- Caused by: fr.inria.corese.sparql.triple.javacc1.JavaccParseException: Encountered "C:" at line 1, column 1.
 -- Was expecting one of:
 --     <EOF> 
 --     "@base" ...
 --     "@prefix" ...
 --     "@path" ...
 --     <LANGTAG> ...
 --     "base" ...
 --     "prefix" ...
 --     "select" ...
 --     "describe" ...
 --     "construct" ...
 --     "rule" ...
 --     "ask" ...
 --     "template" ...
 --     "load" ...
 --     "clear" ...
 --     "drop" ...
 --     "create" ...
 --     "add" ...
 --     "move" ...
 --     "copy" ...
 --     "insert" ...
 --     "delete" ...
 --     "with" ...
 --     "function" ...
 --     "package" ...
 --     "{" ...
 --     
 -- 	at fr.inria.corese.sparql.triple.javacc1.SparqlCorese.parse(SparqlCorese.java:102)
 -- 	at fr.inria.corese.sparql.triple.parser.ParserSparql1.parse(ParserSparql1.java:70)
 -- 	... 48 more
 -- 
 -- 
```

Attempts to work-around by specifying the file by URL also fail generating file not found errors.

## Possible Solution

This likely requires a code change and may have something to do with how the Java Virtual Machines is referencing or not the local file system from code in the plugin jar.

## Steps to Reproduce

1. Install the SemanticWebImport pluin to Gephi
2. Use Window -> SemanticWebImport to open the interface in Gephi
3. Use the Driver tab with Local Driver - Corese
4. Attempt to add to the RDF resources list

## Context

This makes the plugin unusable without a REST endpoint.

## Your Environment

* Gephi Version used: Gephi 0.10.0
* Plugin Version used: SemanticWebImport 1.4.0
* Operating System: Microsoft Windows 11 Pro 23H2

**Comment by HiroP0** [comment]
Same here. Win10 22H2. SWI 1.4.0- Gephi 0.10.1.

**Comment by stefanches7** [comment]
Same here, Windows 11, Gephi 0.10.1

**Comment by ErwanDemairy** [comment]
same issue than #6
